const DEFAULT = {
    SET_LOADING: 'SET_LOADING',
    SET_QUESTIONS: 'SET_QUESTIONS',
    SET_STEP_POSITION: 'SET_STEP_POSITION',
    SET_SCORE: 'SET_SCORE',
    SET_SCORE_LIST: 'SET_SCORE_LIST',
    PLAY_AGAIN: 'PLAY_AGAIN',
};

export default DEFAULT;
